"""add onboarding fields to user_profiles

Revision ID: f4e5a18f3481
Revises: b4900a105d3f
Create Date: 2026-04-15 19:03:54.073661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4e5a18f3481'
down_revision = 'b4900a105d3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('street_address', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('postal_code', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('middle_name', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('country_of_citizenship', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('country_of_birth', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('country_of_tax_residence', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('disclosures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('agreements_signed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('risk_disclosure_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('attribution_source', sa.Text(), nullable=True))
    # NOTE: Alembic incorrectly detects the cross-schema FK (user_profiles.id → auth.users.id)
    # as removed. Do NOT drop it — it was created via raw SQL in the initial migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'attribution_source')
    op.drop_column('user_profiles', 'risk_disclosure_acknowledged_at')
    op.drop_column('user_profiles', 'agreements_signed')
    op.drop_column('user_profiles', 'disclosures')
    op.drop_column('user_profiles', 'country_of_tax_residence')
    op.drop_column('user_profiles', 'country_of_birth')
    op.drop_column('user_profiles', 'country_of_citizenship')
    op.drop_column('user_profiles', 'middle_name')
    op.drop_column('user_profiles', 'postal_code')
    op.drop_column('user_profiles', 'state')
    op.drop_column('user_profiles', 'city')
    op.drop_column('user_profiles', 'street_address')
    op.drop_column('user_profiles', 'phone_number')
    # ### end Alembic commands ###
