"""add is_deleted to conversations

Revision ID: 10f24d6dff33
Revises: f05ad387f3bf
Create Date: 2026-05-15 13:02:32.878179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f24d6dff33'
down_revision = 'f05ad387f3bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_deleted')
    # ### end Alembic commands ###
