"""Initial Migration

Revision ID: b4900a105d3f
Revises: 
Create Date: 2026-04-03 20:23:29.702339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4900a105d3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Manual: updated_at trigger function (applies to all tables) ---
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_step', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokerage_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alpaca_account_id', sa.Text(), nullable=False),
    sa.Column('account_status', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpaca_account_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('plaid_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.Text(), nullable=False),
    sa.Column('plaid_access_token', sa.Text(), nullable=False),
    sa.Column('plaid_account_id', sa.Text(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('account_mask', sa.Text(), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_table('radar_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('context_blurb', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='ai_generated', nullable=False),
    sa.Column('is_favorited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_items_user_id'), 'radar_items', ['user_id'], unique=False)
    op.create_table('user_financial_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('annual_income', sa.Text(), nullable=True),
    sa.Column('net_worth', sa.Text(), nullable=True),
    sa.Column('risk_tolerance', sa.Text(), nullable=True),
    sa.Column('investment_goals', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('time_horizon', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Text(), nullable=True),
    sa.Column('financial_worries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('liquid_net_worth', sa.Text(), nullable=True),
    sa.Column('income_stability', sa.Text(), nullable=True),
    sa.Column('risk_scenario_response', sa.Text(), nullable=True),
    sa.Column('max_loss_tolerance', sa.Text(), nullable=True),
    sa.Column('employment_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funding_sources', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.Text(), server_default='system', nullable=False),
    sa.Column('text_size', sa.Text(), server_default='standard', nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ai_internet_access', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ach_relationships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brokerage_account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.UUID(), nullable=True),
    sa.Column('alpaca_relationship_id', sa.Text(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('account_mask', sa.Text(), nullable=True),
    sa.Column('account_type', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='QUEUED', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brokerage_account_id'], ['brokerage_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ach_relationships_user_id'), 'ach_relationships', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mcp_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('order_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('alpaca_order_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('notional', sa.Numeric(), nullable=True),
    sa.Column('limit_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(), nullable=True),
    sa.Column('filled_qty', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_user_id'), 'order_events', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Manual: FK from user_profiles.id → auth.users(id) (cross-schema) ---
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT fk_user_profiles_auth_users
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
    """)

    # --- Manual: trigger function to create user_profile on signup ---
    op.execute("""
        CREATE OR REPLACE FUNCTION on_auth_user_created()
        RETURNS TRIGGER AS $$
        BEGIN
            INSERT INTO public.user_profiles (id, email, created_at, updated_at)
            VALUES (NEW.id, NEW.email, now(), now());
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # --- Manual: attach trigger to auth.users ---
    op.execute("""
        CREATE TRIGGER trg_auth_user_created
        AFTER INSERT ON auth.users
        FOR EACH ROW
        EXECUTE FUNCTION on_auth_user_created();
    """)

    # --- Manual: grant so the auth trigger can insert into user_profiles ---
    op.execute("GRANT INSERT ON public.user_profiles TO supabase_auth_admin;")

    # --- Manual: attach updated_at triggers to all tables ---
    for table in [
        'feature_flags',
        'user_profiles',
        'user_financial_profiles',
        'user_settings',
        'brokerage_accounts',
        'plaid_items',
        'ach_relationships',
        'radar_items',
        'conversations',
        'messages',
        'order_events',
    ]:
        op.execute(f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        """)


def downgrade() -> None:
    # --- Manual: drop updated_at triggers ---
    for table in [
        'order_events',
        'messages',
        'conversations',
        'radar_items',
        'ach_relationships',
        'plaid_items',
        'brokerage_accounts',
        'user_settings',
        'user_financial_profiles',
        'user_profiles',
        'feature_flags',
    ]:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")

    # --- Manual: drop auth.users trigger, function, and grant ---
    op.execute("REVOKE INSERT ON public.user_profiles FROM supabase_auth_admin;")
    op.execute("DROP TRIGGER IF EXISTS trg_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS on_auth_user_created();")

    # --- Manual: drop cross-schema FK ---
    op.execute("ALTER TABLE user_profiles DROP CONSTRAINT IF EXISTS fk_user_profiles_auth_users;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_events_user_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ach_relationships_user_id'), table_name='ach_relationships')
    op.drop_table('ach_relationships')
    op.drop_table('user_settings')
    op.drop_table('user_financial_profiles')
    op.drop_index(op.f('ix_radar_items_user_id'), table_name='radar_items')
    op.drop_table('radar_items')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('brokerage_accounts')
    op.drop_table('user_profiles')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###

    # --- Manual: drop updated_at function (after all tables are gone) ---
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
