"""add radar items user symbol unique

Revision ID: f05ad387f3bf
Revises: fe348240efd4
Create Date: 2026-05-08 23:15:23.263589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05ad387f3bf'
down_revision = 'fe348240efd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_radar_items_user_id_symbol', 'radar_items', ['user_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_radar_items_user_id_symbol', 'radar_items', type_='unique')
    # ### end Alembic commands ###
